# Generated by Django 4.0.2 on 2022-02-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Service Request', 'Service Request'), ('Incident', 'Incident'), ('Problem', 'Problem'), ('Change Request', ' Change Request')], default='Service Request', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
