# Generated by Django 4.0.2 on 2022-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0003_alter_ticket_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
